# Generated by Django 5.2.4 on 2025-07-31 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(max_length=50)),
                ('sensor', models.CharField(blank=True, choices=[('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor'), ('light', 'Light Sensor'), ('gas', 'Gas Leak Sensor'), ('motion', 'Motion Sensor')], max_length=20, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.CharField(choices=[('temperature', 'Temperature Sensor'), ('humidity', 'Humidity Sensor'), ('light', 'Light Sensor'), ('gas', 'Gas Leak Sensor'), ('motion', 'Motion Sensor')], max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
